### ISSUE TITLE
Files missing for kitspace.org

### ISSUE THREAD

**Issue by kasbah** [robotsrulz/SP_Adapter#1]
Hello, Gerbers and BOM are now missing for the [kitspace.org page](https://kitspace.org/boards/github.com/robotsrulz/sp_adapter/). I have locked it down to 0391e520c2f1e953f703b467ebe6b8022971771 for now. What's the plan for the kitspace.org page?

**Comment by robotsrulz** [comment]
Please remove my page from kitspace.org, I am no longer interested in being listed. Thank you for your efforts!

**Comment by kasbah** [comment]
I can do this as soon as I am back on my laptop. Can I ask why you no
longer want it to be listed? What would Kitspace need for you to put this
and future projects there?

**Comment by robotsrulz** [comment]
I see no benefit from being listed but I have to maintain all the files in
actual state. It's like manually registering in a search engine that is not
widely used. And I don't feel like somebody needs details about the
project. People I'm usually talking with are only interested in complete
and working solution, not details under the hood.

вт, 10 июл. 2018 г. в 22:38, Kaspar Emanuel <notifications@github.com>:

> I can do this as soon as I am back on my laptop. Can I ask why you no
> longer want it to be listed? What would Kitspace need for you to put this
> and future projects there?
>

**Comment by kasbah** [comment]
That's a shame. Do you mind leaving up the old version as it is for now?
Maybe as I add features and if Kitspace manages to get more popular you
will see more benefit.

Part of the plan is to reduce the maintenance burden by extracting all the
info from the files you use yourself. Once that happens it should be easy
to bring up to date.

I have seen some people clicking through and ordering PCBs for this on the
analytics by the way. Maybe it would be nice to integrate click counts that
everyone can see on the links.

**Comment by robotsrulz** [comment]
I don't mind if you leave the old version however it's up to you.

There is a page on SeeedStudio site offering me 10% from each PCB order and I never received any money from them so I don't care any more. However people ask me about complete boards so I will focus on this now.

**Comment by kasbah** [comment]
Cool, I'll leave it up at that version for now. Let me know if you ever change your mind. 

It makes sense that people prefer a finished product but I thought you would have heard of at least a few people DIYing it. Even if you do get some, I think making money through referrals to the PCB fabs is much more of a challenge. I know because that's how I am trying to make money for Kitspace development and it's not making very much. 

Maybe the future for Kitspace could be in assisting people to get to the finished product and selling that through registering group buys. It could still serve people that want to DIY more niche projects but as you are experiencing, when you have a known working, popular design then most people will just want to have the full solution rather than having to make it themselves. 

I am wondering how you are finding the process of doing these smaller runs and selling them. What are the hardest challenges and what are annoying little things that you feel like should be solved already? 

I know finding buyers is always a challenge and I wish Kitspace was in more of a state to help there. Maybe one day.
